
// Objective-C API for talking to the following Go packages
//
//	github.com/tinfoilanalytics/verifier/pkg/client
//
// File is generated by gomobile bind. Do not edit.
#ifndef __TinfoilVerifier_FRAMEWORK_H__
#define __TinfoilVerifier_FRAMEWORK_H__

#include "Client.objc.h"
#include "Universe.objc.h"

#endif
