// Objective-C API for talking to github.com/tinfoilanalytics/verifier/pkg/client Go package.
//   gobind -lang=objc github.com/tinfoilanalytics/verifier/pkg/client
//
// File is generated by gobind. Do not edit.

#ifndef __Client_H__
#define __Client_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class ClientEnclaveState;
@class ClientResponse;
@class ClientSecureClient;
@class ClientTLSBoundRoundTripper;

@interface ClientEnclaveState : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSData* _Nullable certFingerprint;
@property (nonatomic) NSString* _Nonnull eifHash;
@end

@interface ClientResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull status;
@property (nonatomic) long statusCode;
// skipped field Response.Headers with unsupported type: map[string][]string

@property (nonatomic) NSData* _Nullable body;
@end

@interface ClientSecureClient : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)enclave repo:(NSString* _Nullable)repo;
// skipped method SecureClient.Get with unsupported parameter or return types

// skipped method SecureClient.HTTPClient with unsupported parameter or return types

// skipped method SecureClient.Post with unsupported parameter or return types

/**
 * VerificationState returns the last verified enclave state
 */
- (ClientEnclaveState* _Nullable)verificationState;
/**
 * Verify verifies the enclave against the latest code release
 */
- (ClientEnclaveState* _Nullable)verify:(NSError* _Nullable* _Nullable)error;
@end

@interface ClientTLSBoundRoundTripper : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSData* _Nullable expectedCertFP;
// skipped method TLSBoundRoundTripper.RoundTrip with unsupported parameter or return types

@end

@interface Client : NSObject
+ (NSError* _Nullable) errCertMismatch;
+ (void) setErrCertMismatch:(NSError* _Nullable)v;

+ (NSError* _Nullable) errNoTLS;
+ (void) setErrNoTLS:(NSError* _Nullable)v;

+ (NSError* _Nullable) errNoValidCertificate;
+ (void) setErrNoValidCertificate:(NSError* _Nullable)v;

@end

FOUNDATION_EXPORT ClientSecureClient* _Nullable ClientNewSecureClient(NSString* _Nullable enclave, NSString* _Nullable repo);

#endif
